
build-package:
  stage: deploy
  image: registry.svleddar-gitlab.leddartech.local/devopsadmin/common_docker_images/gcc_cmake_py3:v01.04
  tags:  
    - gcc-cmake-py3-v01.04-mountpoint
  script:
    - export REQUESTS_CA_BUNDLE="/etc/ssl/certs/ca-certificates.crt"
    - cat $PYPIRC > /tmp/.pypirc
    - pip3 install twine
    - pip3 install --upgrade keyrings.alt 
    - python3 setup.py bdist_wheel
    - cp ./build/lib.linux-x86_64-3.6/pioneer/*.so ./pioneer
    - python3 setup.py sdist
    - python3 -m twine upload dist/*.tar.gz -u leddartech -p $PYPI_PWD
    - export TWINE_PASSWORD=${CI_JOB_TOKEN}
    - export TWINE_USERNAME=gitlab-ci-token
    - python3 -m twine upload --repository-url https://svleddar-gitlab.leddartech.local/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*
#    - python3 -m twine upload --repository gitlab dist/pioneer_common_gui-${CI_COMMIT_TAG}-cp36-cp36m-linux_x86_64.whl --config-file /tmp/.pypirc

  only:
    - tags