
build-package:
  stage: deploy
  image: registry.svleddar-gitlab.leddartech.local/devopsadmin/common_docker_images/gcc-cmake-py3:v1.1
  script:
    - export REQUESTS_CA_BUNDLE="/etc/ssl/certs/ca-certificates.crt"
    - cat $PYPIRC > /tmp/.pypirc
    - pip3 install twine
    - pip3 install --upgrade keyrings.alt 
    - python3 setup.py bdist_wheel
    - cp ./build/*.so ./pioneer
    - python3 setup.py sdist
    - python3 -m twine upload --repository gitlab dist/pioneer_common_gui-${CI_COMMIT_TAG}-cp36-cp36m-linux_x86_64.whl --config-file /tmp/.pypirc
    - python3 -m twine upload ./dist/*.tar.gz -u leddartech -p $PYPI_PWD
  only:
    - tags